"""
discatcore.http.endpoints
~~~~~~~~~~~~~~~~~~~~~~~~~

The implementations for Discord API endpoints. These are for internal use only, use
`discatcore.http.HTTPClient` instead.
"""

# this file was auto-generated by scripts/generate_endpoints.py

from .audit_log import *
from .auto_moderation import *
from .channel import *
from .emoji import *
from .guild import *
from .guild_scheduled_event import *
from .guild_template import *
from .invite import *
from .stage_instance import *
from .sticker import *
from .user import *
from .voice import *
