# SPDX-License-Identifier: MIT

# this file was auto-generated by scripts/generate_endpoints.py

from typing import Any, Optional, Union

import discord_typings
from discord_typings import Snowflake

from discatcore.file import BasicFile
from discatcore.http.endpoints.core import EndpointMixin
from discatcore.http.route import Route
from discatcore.types import Unset

__all__ = ("AuditLogEndpoints",)


class AuditLogEndpoints(EndpointMixin):
    def get_guild_audit_log(
        self,
        guild_id: Snowflake,
        *,
        user_id: Snowflake = Unset,
        action_type: int = Unset,
        before: Snowflake = Unset,
        limit: int = Unset,
    ):
        return self.request(
            Route("GET", "/guilds/{guild_id}/audit-logs", guild_id=guild_id),
            query_params={
                "user_id": user_id,
                "action_type": action_type,
                "before": before,
                "limit": limit,
            },
        )
