# SPDX-License-Identifier: MIT

# this file was auto-generated by scripts/generate_endpoints.py

from typing import Optional

import discord_typings
from discord_typings import Snowflake

from ...types import Unset, UnsetOr
from ..route import Route
from .core import EndpointMixin

__all__ = ("AutoModerationEndpoints",)


class AutoModerationEndpoints(EndpointMixin):
    def list_auto_moderation_rules(self, guild_id: Snowflake):
        return self.request(
            Route("GET", "/guilds/{guild_id}/auto-moderation/rules", guild_id=guild_id)
        )

    def get_auto_moderation_rule(self, guild_id: Snowflake, auto_moderation_rule_id: Snowflake):
        return self.request(
            Route(
                "GET",
                "/guilds/{guild_id}/auto-moderation/rules/{auto_moderation_rule_id}",
                guild_id=guild_id,
                auto_moderation_rule_id=auto_moderation_rule_id,
            )
        )

    def create_auto_moderation_rule(
        self,
        guild_id: Snowflake,
        *,
        name: str,
        event_type: discord_typings.AutoModerationEventTypes,
        trigger_type: discord_typings.AutoModerationTriggerTypes,
        trigger_metadata: UnsetOr[discord_typings.AutoModerationTriggerMetadataData] = Unset,
        actions: list[discord_typings.AutoModerationActionData],
        enabled: UnsetOr[bool] = Unset,
        exempt_roles: UnsetOr[list[Snowflake]] = Unset,
        exempt_channels: UnsetOr[list[Snowflake]] = Unset,
        reason: Optional[str] = None,
    ):
        return self.request(
            Route("POST", "/guilds/{guild_id}/auto-moderation/rules", guild_id=guild_id),
            json_params={
                "name": name,
                "event_type": event_type,
                "trigger_type": trigger_type,
                "trigger_metadata": trigger_metadata,
                "actions": actions,
                "enabled": enabled,
                "exempt_roles": exempt_roles,
                "exempt_channels": exempt_channels,
            },
            reason=reason,
        )

    def modify_auto_moderation_rule(
        self,
        guild_id: Snowflake,
        auto_moderation_rule_id: Snowflake,
        *,
        name: UnsetOr[str] = Unset,
        event_type: UnsetOr[discord_typings.AutoModerationEventTypes] = Unset,
        trigger_metadata: UnsetOr[discord_typings.AutoModerationTriggerMetadataData] = Unset,
        actions: UnsetOr[list[discord_typings.AutoModerationActionData]] = Unset,
        enabled: UnsetOr[bool] = Unset,
        exempt_roles: UnsetOr[list[Snowflake]] = Unset,
        exempt_channels: UnsetOr[list[Snowflake]] = Unset,
        reason: Optional[str] = None,
    ):
        return self.request(
            Route(
                "PATCH",
                "/guilds/{guild_id}/auto-moderation/rules/{auto_moderation_rule_id}",
                guild_id=guild_id,
                auto_moderation_rule_id=auto_moderation_rule_id,
            ),
            json_params={
                "name": name,
                "event_type": event_type,
                "trigger_metadata": trigger_metadata,
                "actions": actions,
                "enabled": enabled,
                "exempt_roles": exempt_roles,
                "exempt_channels": exempt_channels,
            },
            reason=reason,
        )

    def delete_auto_moderation_rule(
        self, guild_id: Snowflake, auto_moderation_rule_id: Snowflake, reason: Optional[str] = None
    ):
        return self.request(
            Route(
                "DELETE",
                "/guilds/{guild_id}/auto-moderation/rules/{auto_moderation_rule_id}",
                guild_id=guild_id,
                auto_moderation_rule_id=auto_moderation_rule_id,
            ),
            reason=reason,
        )
