# SPDX-License-Identifier: MIT

# this file was auto-generated by scripts/generate_endpoints.py

from typing import Optional

from discord_typings import Snowflake

from discatcore.http.endpoints.core import EndpointMixin
from discatcore.http.route import Route
from discatcore.types import Unset

__all__ = ("EmojiEndpoints",)


class EmojiEndpoints(EndpointMixin):
    def list_guild_emojis(self, guild_id: Snowflake):
        return self.request(Route("GET", "/guilds/{guild_id}/emojis", guild_id=guild_id))

    def get_guild_emoji(self, guild_id: Snowflake, emoji_id: Snowflake):
        return self.request(
            Route(
                "GET", "/guilds/{guild_id}/emojis/{emoji_id}", guild_id=guild_id, emoji_id=emoji_id
            )
        )

    def create_guild_emoji(
        self,
        guild_id: Snowflake,
        *,
        name: str,
        image: str,
        roles: list[Snowflake],
        reason: Optional[str] = None,
    ):
        return self.request(
            Route("POST", "/guilds/{guild_id}/emojis", guild_id=guild_id),
            json_params={"name": name, "image": image, "roles": roles},
            reason=reason,
        )

    def modify_guild_emoji(
        self,
        guild_id: Snowflake,
        emoji_id: Snowflake,
        *,
        name: str = Unset,
        roles: list[Snowflake] = Unset,
        reason: Optional[str] = None,
    ):
        return self.request(
            Route(
                "PATCH",
                "/guilds/{guild_id}/emojis/{emoji_id}",
                guild_id=guild_id,
                emoji_id=emoji_id,
            ),
            json_params={"name": name, "roles": roles},
            reason=reason,
        )

    def delete_guild_emoji(
        self, guild_id: Snowflake, emoji_id: Snowflake, reason: Optional[str] = None
    ):
        return self.request(
            Route(
                "DELETE",
                "/guilds/{guild_id}/emojis/{emoji_id}",
                guild_id=guild_id,
                emoji_id=emoji_id,
            ),
            reason=reason,
        )
