# SPDX-License-Identifier: MIT

# this file was auto-generated by scripts/generate_endpoints.py

from typing import Optional

import discord_typings
from discord_typings import Snowflake

from ...file import BasicFile
from ...types import Unset, UnsetOr
from ..route import Route
from .core import EndpointMixin

__all__ = ("InteractionEndpoints",)


class InteractionEndpoints(EndpointMixin):
    def create_interaction_response(
        self,
        interaction_id: Snowflake,
        interaction_token: str,
        *,
        type: discord_typings.InteractionCallbackTypes,
        data: UnsetOr[discord_typings.InteractionCallbackData] = Unset,
        files: UnsetOr[list[BasicFile]] = Unset,
    ):
        return self.request(
            Route(
                "POST",
                "/interactions/{interaction_id}/{interaction_token}/callback",
                interaction_id=interaction_id,
                interaction_token=interaction_token,
            ),
            json_params={"type": type, "data": data},
            files=files,
        )

    def get_original_interaction_response(self, application_id: Snowflake, interaction_token: str):
        return self.request(
            Route(
                "GET",
                "/webhooks/{application_id}/{interaction_token}/messages/@original",
                application_id=application_id,
                interaction_token=interaction_token,
            )
        )

    def edit_original_interaction_response(
        self,
        application_id: Snowflake,
        interaction_token: str,
        *,
        content: UnsetOr[Optional[str]] = Unset,
        embeds: UnsetOr[Optional[list[discord_typings.EmbedData]]] = Unset,
        allowed_mentions: UnsetOr[Optional[discord_typings.AllowedMentionsData]] = Unset,
        components: UnsetOr[Optional[list[discord_typings.ComponentData]]] = Unset,
        attachments: UnsetOr[Optional[list[discord_typings.PartialAttachmentData]]] = Unset,
        files: UnsetOr[list[BasicFile]] = Unset,
    ):
        return self.request(
            Route(
                "PATCH",
                "/webhooks/{application_id}/{interaction_token}/messages/@original",
                application_id=application_id,
                interaction_token=interaction_token,
            ),
            json_params={
                "content": content,
                "embeds": embeds,
                "allowed_mentions": allowed_mentions,
                "components": components,
                "attachments": attachments,
            },
            files=files,
        )

    def delete_original_interaction_response(
        self, application_id: Snowflake, interaction_token: str
    ):
        return self.request(
            Route(
                "DELETE",
                "/webhooks/{application_id}/{interaction_token}/messages/@original",
                application_id=application_id,
                interaction_token=interaction_token,
            )
        )

    def create_followup_message(
        self,
        application_id: Snowflake,
        interaction_token: str,
        *,
        content: UnsetOr[str] = Unset,
        tts: UnsetOr[bool] = Unset,
        embeds: UnsetOr[list[discord_typings.EmbedData]] = Unset,
        allowed_mentions: UnsetOr[discord_typings.AllowedMentionsData] = Unset,
        components: UnsetOr[list[discord_typings.ComponentData]] = Unset,
        attachments: UnsetOr[list[discord_typings.PartialAttachmentData]] = Unset,
        flags: UnsetOr[int] = Unset,
        thread_name: UnsetOr[str] = Unset,
        files: UnsetOr[list[BasicFile]] = Unset,
    ):
        return self.request(
            Route(
                "POST",
                "/webhooks/{application_id}/{interaction_token}",
                application_id=application_id,
                interaction_token=interaction_token,
            ),
            json_params={
                "content": content,
                "tts": tts,
                "embeds": embeds,
                "allowed_mentions": allowed_mentions,
                "components": components,
                "attachments": attachments,
                "flags": flags,
                "thread_name": thread_name,
            },
            files=files,
        )

    def get_followup_message(
        self, application_id: Snowflake, interaction_token: str, message_id: Snowflake
    ):
        return self.request(
            Route(
                "GET",
                "/webhooks/{application_id}/{interaction_token}/messages/{message_id}",
                application_id=application_id,
                interaction_token=interaction_token,
                message_id=message_id,
            )
        )

    def edit_followup_message(
        self,
        application_id: Snowflake,
        interaction_token: str,
        message_id: Snowflake,
        *,
        content: UnsetOr[Optional[str]] = Unset,
        embeds: UnsetOr[Optional[list[discord_typings.EmbedData]]] = Unset,
        allowed_mentions: UnsetOr[Optional[discord_typings.AllowedMentionsData]] = Unset,
        components: UnsetOr[Optional[list[discord_typings.ComponentData]]] = Unset,
        attachments: UnsetOr[Optional[list[discord_typings.PartialAttachmentData]]] = Unset,
        files: UnsetOr[list[BasicFile]] = Unset,
    ):
        return self.request(
            Route(
                "PATCH",
                "/webhooks/{application_id}/{interaction_token}/messages/{message_id}",
                application_id=application_id,
                interaction_token=interaction_token,
                message_id=message_id,
            ),
            json_params={
                "content": content,
                "embeds": embeds,
                "allowed_mentions": allowed_mentions,
                "components": components,
                "attachments": attachments,
            },
            files=files,
        )

    def delete_followup_message(
        self, application_id: Snowflake, interaction_token: str, message_id: Snowflake
    ):
        return self.request(
            Route(
                "DELETE",
                "/webhooks/{application_id}/{interaction_token}/messages/{message_id}",
                application_id=application_id,
                interaction_token=interaction_token,
                message_id=message_id,
            )
        )
