# SPDX-License-Identifier: MIT

# this file was auto-generated by scripts/generate_endpoints.py


from discatcore.http.endpoints.core import EndpointMixin
from discatcore.http.route import Route

__all__ = ("VoiceEndpoints",)


class VoiceEndpoints(EndpointMixin):
    def list_voice_regions(self):
        return self.request(Route("GET", "/voice/regions"))
