# SPDX-License-Identifier: MIT

# this file was auto-generated by scripts/generate_endpoints.py

from typing import Any, Optional, Union

import discord_typings
from discord_typings import Snowflake

from discatcore.file import BasicFile
from discatcore.http.endpoints.core import EndpointMixin
from discatcore.http.route import Route
from discatcore.types import Unset

__all__ = ("VoiceEndpoints",)


class VoiceEndpoints(EndpointMixin):
    def list_voice_regions(self):
        return self.request(Route("GET", "/voice/regions"))
